# Generated by Django 3.0.7 on 2020-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopqrdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrdata', models.TextField()),
                ('shopid', models.BigIntegerField()),
            ],
        ),
    ]
