# Generated by Django 3.0.7 on 2020-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='shopname',
            field=models.CharField(default='Unnamed Shop', max_length=50),
        ),
    ]
