# Generated by Django 3.0.7 on 2020-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200719_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='shopcategoty',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('food', 'Food'), ('grocery', 'Grocery'), ('electronics', 'Electronics'), ('handcrafts', 'Handcrafts'), ('stationary', 'Stationary'), ('garments', 'Garments')], max_length=30, null=True),
        ),
    ]
