# Generated by Django 3.0.7 on 2020-08-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0002_auto_20200720_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='referralfirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardpoint', models.FloatField(default=0)),
                ('referrerid', models.BigIntegerField(default=-1, null=True)),
                ('freedelivery', models.BooleanField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='buyer.BuyerProfile')),
            ],
        ),
    ]
