# Generated by Django 3.0.7 on 2020-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='referralrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('phoneno', models.BigIntegerField()),
                ('rewardpoint', models.BigIntegerField()),
                ('option', models.CharField(choices=[('paytm', 'PAYTM'), ('amazonpay', 'AMAZON PAY'), ('recharge', 'RECHARGE')], max_length=20)),
                ('additionalphoneno', models.BigIntegerField(default='', null=True)),
                ('coupon', models.TextField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
