# Generated by Django 3.0.7 on 2020-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(default='{"address": []}'),
        ),
    ]
