# Generated by Django 3.0.7 on 2020-07-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
        ('buyer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllIndiaPinCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('officetype', models.TextField(blank=True, db_column='officeType', null=True)),
                ('deliverystatus', models.TextField(blank=True, db_column='Deliverystatus', null=True)),
                ('divisionname', models.TextField(blank=True, null=True)),
                ('regionname', models.TextField(blank=True, null=True)),
                ('circlename', models.TextField(blank=True, null=True)),
                ('taluk', models.TextField(blank=True, db_column='Taluk', null=True)),
                ('districtname', models.TextField(blank=True, db_column='Districtname', null=True)),
                ('statename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_india_pin_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('originofproduct', models.CharField(max_length=50)),
                ('available', models.IntegerField()),
                ('review', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(default='default/product.jpg', upload_to='shop/product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdatas', to='seller.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('orderedon', models.DateTimeField(auto_now_add=True)),
                ('deliverdon', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('details', models.TextField(null=True)),
                ('sellerid', models.CharField(max_length=500, null=True)),
                ('homedelivery', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderhistories', to='buyer.BuyerProfile')),
            ],
        ),
    ]
