# Generated by Django 3.1.2 on 2021-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0002_auto_20200819_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDefinitionsForDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleName', models.CharField(default='', max_length=100, null=True)),
                ('basePricePerKm', models.FloatField(default=0.0, null=True)),
                ('basePriceAvailableForRangeInKm', models.FloatField(default=0.0, null=True)),
                ('extraPricePerKm', models.FloatField(default=0.0, null=True)),
                ('pincodeOverride', models.IntegerField(blank=True, null=True)),
                ('priceHikeByTimeStatus', models.BooleanField(default=False, null=True)),
                ('priceHikeAfterTime', models.TimeField(blank=True, null=True)),
                ('additionalCostForPriceHike', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
