# Generated by Django 3.1.2 on 2021-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0004_auto_20210717_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTokenDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.TextField(default='', null=True)),
                ('fcmtoken', models.TextField(default='', null=True)),
            ],
        ),
    ]
